//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_SoapGestionProduit2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.adame.com/", ConfigurationName="ServiceReference1.RegistrerProduits")]
    public interface RegistrerProduits {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitObjetRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitObjetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetResponse insertProduitObjet(WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitObjetRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitObjetResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetResponse> insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifResponse insertProduitPrimitif(WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifResponse> insertProduitPrimitifAsync(WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/augmenterQteRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/augmenterQteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference1.augmenterQteResponse augmenterQte(WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/augmenterQteRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/augmenterQteResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.augmenterQteResponse> augmenterQteAsync(WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/modifierQteRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/modifierQteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference1.modifierQteResponse modifierQte(WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/modifierQteRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/modifierQteResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.modifierQteResponse> modifierQteAsync(WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/getListProduitsRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/getListProduitsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference1.getListProduitsResponse getListProduits(WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/getListProduitsRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/getListProduitsResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.getListProduitsResponse> getListProduitsAsync(WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/getAllProduitsRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/getAllProduitsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference1.getAllProduitsResponse getAllProduits(WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/getAllProduitsRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/getAllProduitsResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.getAllProduitsResponse> getAllProduitsAsync(WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.adame.com/")]
    public partial class produit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomField;
        
        private double prixField;
        
        private int qteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
                this.RaisePropertyChanged("prix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int qte {
            get {
                return this.qteField;
            }
            set {
                this.qteField = value;
                this.RaisePropertyChanged("qte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitObjet", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitObjetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WC_SoapGestionProduit2.ServiceReference1.produit produit;
        
        public insertProduitObjetRequest() {
        }
        
        public insertProduitObjetRequest(WC_SoapGestionProduit2.ServiceReference1.produit produit) {
            this.produit = produit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitObjetResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitObjetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public insertProduitObjetResponse() {
        }
        
        public insertProduitObjetResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitPrimitif", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitPrimitifRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int qte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double prix;
        
        public insertProduitPrimitifRequest() {
        }
        
        public insertProduitPrimitifRequest(string nom, int qte, double prix) {
            this.nom = nom;
            this.qte = qte;
            this.prix = prix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitPrimitifResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitPrimitifResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public insertProduitPrimitifResponse() {
        }
        
        public insertProduitPrimitifResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="augmenterQte", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class augmenterQteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int qte;
        
        public augmenterQteRequest() {
        }
        
        public augmenterQteRequest(string nom, int qte) {
            this.nom = nom;
            this.qte = qte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="augmenterQteResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class augmenterQteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public augmenterQteResponse() {
        }
        
        public augmenterQteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifierQte", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class modifierQteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int qte;
        
        public modifierQteRequest() {
        }
        
        public modifierQteRequest(string nom, int qte) {
            this.nom = nom;
            this.qte = qte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifierQteResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class modifierQteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public modifierQteResponse() {
        }
        
        public modifierQteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListProduits", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class getListProduitsRequest {
        
        public getListProduitsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListProduitsResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class getListProduitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getListProduitsResponse() {
        }
        
        public getListProduitsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProduits", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class getAllProduitsRequest {
        
        public getAllProduitsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProduitsResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class getAllProduitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WC_SoapGestionProduit2.ServiceReference1.produit[] @return;
        
        public getAllProduitsResponse() {
        }
        
        public getAllProduitsResponse(WC_SoapGestionProduit2.ServiceReference1.produit[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrerProduitsChannel : WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrerProduitsClient : System.ServiceModel.ClientBase<WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits>, WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits {
        
        public RegistrerProduitsClient() {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrerProduitsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetResponse WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.insertProduitObjet(WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest request) {
            return base.Channel.insertProduitObjet(request);
        }
        
        public string insertProduitObjet(WC_SoapGestionProduit2.ServiceReference1.produit produit) {
            WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest();
            inValue.produit = produit;
            WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetResponse retVal = ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).insertProduitObjet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetResponse> WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest request) {
            return base.Channel.insertProduitObjetAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetResponse> insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference1.produit produit) {
            WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.insertProduitObjetRequest();
            inValue.produit = produit;
            return ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).insertProduitObjetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifResponse WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.insertProduitPrimitif(WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest request) {
            return base.Channel.insertProduitPrimitif(request);
        }
        
        public string insertProduitPrimitif(string nom, int qte, double prix) {
            WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            inValue.prix = prix;
            WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifResponse retVal = ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).insertProduitPrimitif(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifResponse> WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.insertProduitPrimitifAsync(WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest request) {
            return base.Channel.insertProduitPrimitifAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifResponse> insertProduitPrimitifAsync(string nom, int qte, double prix) {
            WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.insertProduitPrimitifRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            inValue.prix = prix;
            return ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).insertProduitPrimitifAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference1.augmenterQteResponse WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.augmenterQte(WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest request) {
            return base.Channel.augmenterQte(request);
        }
        
        public string augmenterQte(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            WC_SoapGestionProduit2.ServiceReference1.augmenterQteResponse retVal = ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).augmenterQte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.augmenterQteResponse> WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.augmenterQteAsync(WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest request) {
            return base.Channel.augmenterQteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.augmenterQteResponse> augmenterQteAsync(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.augmenterQteRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            return ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).augmenterQteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference1.modifierQteResponse WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.modifierQte(WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest request) {
            return base.Channel.modifierQte(request);
        }
        
        public string modifierQte(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            WC_SoapGestionProduit2.ServiceReference1.modifierQteResponse retVal = ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).modifierQte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.modifierQteResponse> WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.modifierQteAsync(WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest request) {
            return base.Channel.modifierQteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.modifierQteResponse> modifierQteAsync(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.modifierQteRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            return ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).modifierQteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference1.getListProduitsResponse WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.getListProduits(WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest request) {
            return base.Channel.getListProduits(request);
        }
        
        public string[] getListProduits() {
            WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest();
            WC_SoapGestionProduit2.ServiceReference1.getListProduitsResponse retVal = ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).getListProduits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.getListProduitsResponse> WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.getListProduitsAsync(WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest request) {
            return base.Channel.getListProduitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.getListProduitsResponse> getListProduitsAsync() {
            WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.getListProduitsRequest();
            return ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).getListProduitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference1.getAllProduitsResponse WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.getAllProduits(WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest request) {
            return base.Channel.getAllProduits(request);
        }
        
        public WC_SoapGestionProduit2.ServiceReference1.produit[] getAllProduits() {
            WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest();
            WC_SoapGestionProduit2.ServiceReference1.getAllProduitsResponse retVal = ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).getAllProduits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.getAllProduitsResponse> WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits.getAllProduitsAsync(WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest request) {
            return base.Channel.getAllProduitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference1.getAllProduitsResponse> getAllProduitsAsync() {
            WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest inValue = new WC_SoapGestionProduit2.ServiceReference1.getAllProduitsRequest();
            return ((WC_SoapGestionProduit2.ServiceReference1.RegistrerProduits)(this)).getAllProduitsAsync(inValue);
        }
    }
}
