//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_SoapGestionProduit2.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.adame.com/", ConfigurationName="ServiceReference2.RegistrerProduits")]
    public interface RegistrerProduits {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitObjetRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitObjetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetResponse insertProduitObjet(WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitObjetRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitObjetResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetResponse> insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.adame.com/")]
    public partial class produit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomField;
        
        private double prixField;
        
        private int qteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
                this.RaisePropertyChanged("prix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int qte {
            get {
                return this.qteField;
            }
            set {
                this.qteField = value;
                this.RaisePropertyChanged("qte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitObjet", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitObjetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WC_SoapGestionProduit2.ServiceReference2.produit produit;
        
        public insertProduitObjetRequest() {
        }
        
        public insertProduitObjetRequest(WC_SoapGestionProduit2.ServiceReference2.produit produit) {
            this.produit = produit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitObjetResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitObjetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public insertProduitObjetResponse() {
        }
        
        public insertProduitObjetResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrerProduitsChannel : WC_SoapGestionProduit2.ServiceReference2.RegistrerProduits, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrerProduitsClient : System.ServiceModel.ClientBase<WC_SoapGestionProduit2.ServiceReference2.RegistrerProduits>, WC_SoapGestionProduit2.ServiceReference2.RegistrerProduits {
        
        public RegistrerProduitsClient() {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrerProduitsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetResponse WC_SoapGestionProduit2.ServiceReference2.RegistrerProduits.insertProduitObjet(WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest request) {
            return base.Channel.insertProduitObjet(request);
        }
        
        public string insertProduitObjet(WC_SoapGestionProduit2.ServiceReference2.produit produit) {
            WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest inValue = new WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest();
            inValue.produit = produit;
            WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetResponse retVal = ((WC_SoapGestionProduit2.ServiceReference2.RegistrerProduits)(this)).insertProduitObjet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetResponse> WC_SoapGestionProduit2.ServiceReference2.RegistrerProduits.insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest request) {
            return base.Channel.insertProduitObjetAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetResponse> insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference2.produit produit) {
            WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest inValue = new WC_SoapGestionProduit2.ServiceReference2.insertProduitObjetRequest();
            inValue.produit = produit;
            return ((WC_SoapGestionProduit2.ServiceReference2.RegistrerProduits)(this)).insertProduitObjetAsync(inValue);
        }
    }
}
