//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_SoapGestionProduit2.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.adame.com/", ConfigurationName="ServiceReference.RegistrerProduits")]
    public interface RegistrerProduits {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifResponse insertProduitPrimitif(WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitPrimitifResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifResponse> insertProduitPrimitifAsync(WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitObjetRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitObjetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference.insertProduitObjetResponse insertProduitObjet(WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/insertProduitObjetRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/insertProduitObjetResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.insertProduitObjetResponse> insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/updateQteRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/updateQteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference.updateQteResponse updateQte(WC_SoapGestionProduit2.ServiceReference.updateQteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/updateQteRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/updateQteResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.updateQteResponse> updateQteAsync(WC_SoapGestionProduit2.ServiceReference.updateQteRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/getAllProduitsRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/getAllProduitsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WC_SoapGestionProduit2.ServiceReference.getAllProduitsResponse getAllProduits(WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.adame.com/RegistrerProduits/getAllProduitsRequest", ReplyAction="http://ws.adame.com/RegistrerProduits/getAllProduitsResponse")]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.getAllProduitsResponse> getAllProduitsAsync(WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitPrimitif", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitPrimitifRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int qte;
        
        public insertProduitPrimitifRequest() {
        }
        
        public insertProduitPrimitifRequest(string nom, int qte) {
            this.nom = nom;
            this.qte = qte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitPrimitifResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitPrimitifResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertProduitPrimitifResponse() {
        }
        
        public insertProduitPrimitifResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.adame.com/")]
    public partial class produit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nomField;
        
        private int qteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("nom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int qte {
            get {
                return this.qteField;
            }
            set {
                this.qteField = value;
                this.RaisePropertyChanged("qte");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitObjet", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitObjetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WC_SoapGestionProduit2.ServiceReference.produit produit;
        
        public insertProduitObjetRequest() {
        }
        
        public insertProduitObjetRequest(WC_SoapGestionProduit2.ServiceReference.produit produit) {
            this.produit = produit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertProduitObjetResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class insertProduitObjetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertProduitObjetResponse() {
        }
        
        public insertProduitObjetResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateQte", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class updateQteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int qte;
        
        public updateQteRequest() {
        }
        
        public updateQteRequest(string nom, int qte) {
            this.nom = nom;
            this.qte = qte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateQteResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class updateQteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateQteResponse() {
        }
        
        public updateQteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProduits", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class getAllProduitsRequest {
        
        public getAllProduitsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllProduitsResponse", WrapperNamespace="http://ws.adame.com/", IsWrapped=true)]
    public partial class getAllProduitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.adame.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WC_SoapGestionProduit2.ServiceReference.produit[] @return;
        
        public getAllProduitsResponse() {
        }
        
        public getAllProduitsResponse(WC_SoapGestionProduit2.ServiceReference.produit[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrerProduitsChannel : WC_SoapGestionProduit2.ServiceReference.RegistrerProduits, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrerProduitsClient : System.ServiceModel.ClientBase<WC_SoapGestionProduit2.ServiceReference.RegistrerProduits>, WC_SoapGestionProduit2.ServiceReference.RegistrerProduits {
        
        public RegistrerProduitsClient() {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrerProduitsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrerProduitsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifResponse WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.insertProduitPrimitif(WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest request) {
            return base.Channel.insertProduitPrimitif(request);
        }
        
        public bool insertProduitPrimitif(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest inValue = new WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifResponse retVal = ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).insertProduitPrimitif(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifResponse> WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.insertProduitPrimitifAsync(WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest request) {
            return base.Channel.insertProduitPrimitifAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifResponse> insertProduitPrimitifAsync(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest inValue = new WC_SoapGestionProduit2.ServiceReference.insertProduitPrimitifRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            return ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).insertProduitPrimitifAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference.insertProduitObjetResponse WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.insertProduitObjet(WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest request) {
            return base.Channel.insertProduitObjet(request);
        }
        
        public bool insertProduitObjet(WC_SoapGestionProduit2.ServiceReference.produit produit) {
            WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest inValue = new WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest();
            inValue.produit = produit;
            WC_SoapGestionProduit2.ServiceReference.insertProduitObjetResponse retVal = ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).insertProduitObjet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.insertProduitObjetResponse> WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest request) {
            return base.Channel.insertProduitObjetAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.insertProduitObjetResponse> insertProduitObjetAsync(WC_SoapGestionProduit2.ServiceReference.produit produit) {
            WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest inValue = new WC_SoapGestionProduit2.ServiceReference.insertProduitObjetRequest();
            inValue.produit = produit;
            return ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).insertProduitObjetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference.updateQteResponse WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.updateQte(WC_SoapGestionProduit2.ServiceReference.updateQteRequest request) {
            return base.Channel.updateQte(request);
        }
        
        public bool updateQte(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference.updateQteRequest inValue = new WC_SoapGestionProduit2.ServiceReference.updateQteRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            WC_SoapGestionProduit2.ServiceReference.updateQteResponse retVal = ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).updateQte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.updateQteResponse> WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.updateQteAsync(WC_SoapGestionProduit2.ServiceReference.updateQteRequest request) {
            return base.Channel.updateQteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.updateQteResponse> updateQteAsync(string nom, int qte) {
            WC_SoapGestionProduit2.ServiceReference.updateQteRequest inValue = new WC_SoapGestionProduit2.ServiceReference.updateQteRequest();
            inValue.nom = nom;
            inValue.qte = qte;
            return ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).updateQteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WC_SoapGestionProduit2.ServiceReference.getAllProduitsResponse WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.getAllProduits(WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest request) {
            return base.Channel.getAllProduits(request);
        }
        
        public WC_SoapGestionProduit2.ServiceReference.produit[] getAllProduits() {
            WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest inValue = new WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest();
            WC_SoapGestionProduit2.ServiceReference.getAllProduitsResponse retVal = ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).getAllProduits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.getAllProduitsResponse> WC_SoapGestionProduit2.ServiceReference.RegistrerProduits.getAllProduitsAsync(WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest request) {
            return base.Channel.getAllProduitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WC_SoapGestionProduit2.ServiceReference.getAllProduitsResponse> getAllProduitsAsync() {
            WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest inValue = new WC_SoapGestionProduit2.ServiceReference.getAllProduitsRequest();
            return ((WC_SoapGestionProduit2.ServiceReference.RegistrerProduits)(this)).getAllProduitsAsync(inValue);
        }
    }
}
